[package]
name = "ferio-cli"
version = "0.1.0"
edition = "2021"

[dependencies]
ansi_term = "0.12"
clap = { version = "3.2.21", features = ["derive"] }
color-eyre = { version = "0.6", default-features = false }
tokio = { version = "1", features = ["full"] }
ferio = { path = "../ferio" }
