[package]
name = "ferio-api"
version = "0.1.0"
edition = "2021"

[dependencies]
axum = "0.5"
ferio = { path = "../ferio" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"] }
