name: Deno Deploy
on: [push]

jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Clone repository
        uses: actions/checkout@v2

      - name: Upload to Deno Deploy
        uses: denoland/deployctl@v1
        with:
          project: "ferio-bot"
          entrypoint: "./ferio-bot/main.ts"
